### ISSUE TITLE
Include JavaScript in repo, or build config that CDNs understand

### ISSUE THREAD

**Issue by coolaj86** [paulmillr/noble-hashes#39]
I'd like to be able to use RIPEMD160 from a CDN like unpkg or cdnjs or GitHub Pages.

Would you be open to publishing a `./dist` folder as part of an `npm prepublish` step, or something like that so that it's easier to test this out in a browser?

I see that GitHub Releases has the full bundle, but it's HUGE if all you need is one algo.

**Comment by paulmillr** [comment]
>I see that GitHub Releases has the full bundle, but it's HUGE if all you need is one algo.

If your concern is this, then, consider cases of almost all other users, who don't use unpkg and cdnjs. Adding a `dist` directory would increase package size for the 99+% of users by 30-40%. 

My point remains the same: it's not us, who need to fix package for `unpkg`, it's `unpkg` who needs to get their shit together, follow all ESM rules and ensure they work properly with noble-hashes.

**Comment by coolaj86** [comment]
But why ESM? Why not just use JavaScript?

All ESM does is break old things and doesn't make new things better, more efficient, easier to use or otherwise... better.

What about publishing to JS files to GitHub Releases?

**Comment by paulmillr** [comment]
>But why ESM? Why not just use JavaScript?

ESM is javascript. It is the official module standard for JS, also supported in deno. Common.js modules were never an official standard: they have just been a workaround.

Almost every js builder these days supports ESM. If your tool does not support ESM, the tool is bad. unpkg supports ESM, but not fully — there seem to be some issues with noble packages.

The amount of packages that use pure ESM increases every day. At this point it's impossible to use these packages in old, common.js environments. On a contrary, if you're using ESM in your app, common.js modules can be used without hassle. But not wise-versa.

So if it's viral, you *need* to upgrade to esm. Staying on common.js will break your app some time in the future, when some new module upgrades.

> All ESM does is break old things and doesn't make new things better, more efficient, easier to use or otherwise... better.

It's not up to me to write about benefits of ESM. I'm sure there are many though.

My job is just to support it, because it's the future. Proper ESM support means bundlers will consume it easily. Unless it's shitty bundler, like unpkg.

> What about publishing to JS files to GitHub Releases?

I already publish full noble-hashes.js to gh releases. If you need just one module, you're free to build it on your own. Building 15 standalone files and uploading them to gh releases every release is tiresome.

Also, instead of dealing with these problems, you could just use a bundler that supports tree shaking, such as rollup, and just import noble-hashes from NPM. This is what most folks do these days.
